chat/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'post/$', views.post, name='post'),
    url(r'^messages/$', views.messages, name='messages'),
]

project/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^', include('chat.urls', namespace="chat")),
]

chat/models.py
from django.contrib.auth.models import User
from django.db import models


# Create your models here.
class Chat(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    message = models.CharField(max_length=255)
    user = models.ForeignKey(User)

    def __str__(self):
        return self.message

chat/views.py
from django.http import HttpResponse
from django.http import JsonResponse
from django.shortcuts import render

# Create your views here.
from chat.models import Chat


def home(request):
    chats = Chat.objects.all()
    ctx = {
        'home': 'active',
        'chat': chats
    }
    if request.user.is_authenticated:
        return render(request, 'chat.html', ctx)
    else:
        return render(request, 'base.html', None)


def post(request):
    if request.method == "POST":
        msg = request.POST.get('msgbox', None)
        print('Our value = ', msg)
        chat_message = Chat(user=request.user, message=msg)
        if msg != '':
            chat_message.save()
        return JsonResponse({'msg': msg, 'user': chat_message.user.username})
    else:
        return HttpResponse('Request must be POST.')


def messages(request):
    chat = Chat.objects.all()
    return render(request, 'messages.html', {'chat': chat})

templates/base.html
{% load staticfiles %}
{% load i18n %}
{% load account %}
{% load crispy_forms_tags %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Chat</title>
    {% include "head_css.html" %}
    {% block extra_css %}{% endblock %}
    {% block extra_js %}{% endblock %}
</head>
<body>
{% block navbar %}
    <nav class="navbar navbar-default">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                        aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand"Chat</a>
            </div>
            <div id="navbar" class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li class="active"><a href="#">Home</a></li>
                    {% if user.is_authenticated %}
                        <li><p class="navbar-text">Signed in as <b>{{ user.username }}</b></p></li>
                    {% else %}
                    {% endif %}
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    {% if request.user.is_anonymous %}
                        <a href="/accounts/login/">
                            <button type="button" class="btn navbar-btn btn-success">Sign in</button>
                        </a>
                        <a href="/accounts/signup/">
                            <button type="button" class="btn navbar-btn btn-success">Register</button>
                        </a>
                    {% else %}
                        <a href="/accounts/logout/">
                            <button type="button" class="btn btn-danger navbar-btn">Log out</button>
                        </a>
                    {% endif %}
                </ul>
            </div><!--/.nav-collapse -->
        </div>
    </nav>
{% endblock navbar %}



{% block content %}
    <header class="body-header">
        <div class="body-header__title">
            <h1 class="text-center">Simple chat</h1>
        </div>
    </header>
    <div class="container">
        <div class="row">
            <p class="lead text-center">Login before using chat!</p>
        </div>
    </div>

{% endblock %}


<script src="{% static 'chat/js/jquery-1.12.3.js' %}"></script>
<script src="{% static 'chat/js/bootstrap.min.js' %}"></script>
<script src="{% static 'chat/js/script.js' %}"></script>
</body>
</html>

templates/chat.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <div id="chat-body" class="panel panel-default">
            <div class="panel-heading">Chat Box</div>
            <div id="msg-list-div" class="panel-body">
                <ul id="msg-list" class="list-group">
                    {% for obj in chat %}
                        {% if obj.user == request.user %}
                            <li class="text-right list-group-item">{{ obj.message }}</li>
                        {% else %}
                            <li class="text-left list-group-item">{{ obj.message }}</li>
                        {% endif %}
                    {% empty %}
                        <li class="text-right list-group-item">No messages yet!</li>
                    {% endfor %}
                </ul>
            </div>
        </div>

        <form id="chat-form" method="post" action="{% url 'chat:post' %}" data-spy="affix" data-offset-bottom="10">
            {% csrf_token %}
            <div id="chat-bottom" class="input-group">
                <input type="text" id="chat-msg" name="chat-msg" class="form-control"/>
                <span class="input-group-btn">
                <input class="btn btn-default" id="send" type="submit" value="Send"/>
            </span>
            </div>
        </form>
    </div>
{% endblock content %}

templates/head_css.html
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'chat/css/bootstrap.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'chat/css/style.css' %}">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.4/css/bootstrap-datepicker3.min.css">

templates/messages.html
{% for obj in chat %}
    {% if obj.user == request.user %}
        <li class="text-right list-group-item">{{ obj.message }}</li>
    {% else %}
        <li class="text-left list-group-item">{{ obj.message }}</li>
    {% endif %}
{% empty %}
    <li class="text-right list-group-item">No messages yet!</li>
{% endfor %}